### ISSUE TITLE
cocoapod fails to build on latest xcode

### ISSUE THREAD

**Issue by elprl** [acerbetti/ACEDrawingView#38]
My Swift project shows a build error that fails to recognise UIColor strangely. I fixed this by adding:
#import UIKit/UIKit.h
to ACEDrawingTools.h

**Comment by acerbetti** [comment]
Interesting, I don't use swift...

thanks for reporting this

**Comment by drdaz** [comment]
This isn't unique to Swift actually... I've had to do the same in my objective c projects. It's because ACEDrawingTools does have a dependency on UIKit, but the import is only declared in the -Prefix.pch of the ACEDrawingViewDemo project. So if you use it in your own projects, you need to import it yourself somewhere.

**Comment by elprl** [comment]
Hi, thanks for your response.

Yep, adding the import to the pch file would also fix this. I recommend adding the import to your class though as one of the goals of cocoapods is to make libs independent of other each. Otherwise, you'll have to add the step to your install description. Hope you can find the time to continue working with the project, it's a useful lib for many people I imagine.

**Comment by acerbetti** [comment]
Fixed and updated cocoapods. Thanks
